server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      # 1. Configuración Global de CORS (La que manda)
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      # 2. FILTRO MÁGICO: Elimina duplicados si el microservicio también envía CORS
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

      # 3. Rutas
      routes:
        - id: ms-catalogo
          uri: ${CATALOGO_URI}
          predicates:
            - Path=/api/medicamentos/**
            
        - id: ms-inventario
          uri: ${INVENTARIO_URI}
          predicates:
            - Path=/api/inventarios/**, /api/sucursales/**
            
        - id: ms-ventas
          uri: ${VENTAS_URI}
          predicates:
            - Path=/api/ventas/**