server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      # 1. Configuración de CORS (Permite que React se conecte)
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "*"
            allowedHeaders: "*"

      # 2. Rutas de los Microservicios
      routes:
        - id: ms-catalogo
          uri: ${CATALOGO_URI}
          predicates:
            - Path=/api/medicamentos/**
            
        - id: ms-inventario
          uri: ${INVENTARIO_URI}
          predicates:
            - Path=/api/inventarios/**, /api/sucursales/**
            
        - id: ms-ventas
          uri: ${VENTAS_URI}
          predicates:
            - Path=/api/ventas/**