# --- ETAPA 1: Construcción (Usamos Maven con Java 21) ---
FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

# --- ETAPA 2: Ejecución (Usamos Java 21 ligero) ---
FROM eclipse-temurin:21-jre-alpine
VOLUME /tmp
COPY --from=build /app/target/*.jar app.jar
EXPOSE 9000
ENTRYPOINT ["java","-jar","/app.jar"]