spring.application.name=ms-catalogo
server.port=${SERVER_PORT:8081}

spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:db_catalogo}?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:12345}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

# CONFIGURACIÓN OAUTH2 PARA DOCKER

# 1. Identidad Lógica (lo que viene escrito dentro del token desde el navegador)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9000

# 2. Ubicación Física (a dónde va el microservicio DENTRO de Docker para pedir las llaves)
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://oauth-server:9000/oauth2/jwks