spring.application.name=oauth-server
server.port=9000

# Configuración Base de Datos (Se sobrescribirá con variables de entorno al desplegar)
spring.datasource.url=${DB_URL:jdbc:postgresql://postgres-db:5432/db_oauth}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:admin}
spring.jpa.hibernate.ddl-auto=update

# --- CONFIGURACIÓN CRÍTICA PARA CLOUD RUN ---
# Esto permite que Spring Boot sepa que está detrás de un proxy HTTPS
server.forward-headers-strategy=native
server.tomcat.remote-ip-header=x-forwarded-for
server.tomcat.protocol-header=x-forwarded-proto
server.tomcat.internal-proxies=.*

# --- ISSUER URL ---
# Usamos una variable de entorno con un valor por defecto seguro
spring.security.oauth2.authorizationserver.issuer=${OAUTH_ISSUER_URL}