spring.application.name=oauth-server
server.port=9000

# Configuración de Base de Datos PostgreSQL
spring.datasource.url=jdbc:postgresql://postgres-db:5432/db_oauth
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuración OAuth2 Authorization Server
spring.security.oauth2.authorizationserver.issuer=http://34.130.207.184:9000

logging.level.org.springframework.security=TRACE
server.servlet.session.cookie.name=OAUTH_SESSIONID